2021-11-18 16:51:14,199 ERROR: Exception on /new_study/data_analysis/7431d4a5-bbe8-47c2-828f-877210b9cceb [GET] [in C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\noudy\PycharmProjects\PLS\app\new_study\routes.py", line 831, in data_analysis
    plspm_calc = Plspm(df, config, Scheme.CENTROID)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\plspm\plspm.py", line 65, in __init__
    correction = np.sqrt(filtered_data.shape[0] / (filtered_data.shape[0] - 1))
ZeroDivisionError: division by zero
2021-11-18 17:12:02,993 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:78]
2021-11-18 17:12:03,153 ERROR: Exception on /new_study/data_analysis/7431d4a5-bbe8-47c2-828f-877210b9cceb [GET] [in C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\noudy\PycharmProjects\PLS\app\new_study\routes.py", line 823, in data_analysis
    influenced_variables.append(influenced.abbreviation)
AttributeError: 'BaseQuery' object has no attribute 'abbreviation'
2021-11-18 17:12:19,544 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:78]
2021-11-18 17:12:19,878 ERROR: Exception on /new_study/data_analysis/7431d4a5-bbe8-47c2-828f-877210b9cceb [GET] [in C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\noudy\PycharmProjects\PLS\app\new_study\routes.py", line 824, in data_analysis
    structure.add_path([corevariable.abbreviation], [influenced_variables])
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\plspm\config.py", line 49, in add_path
    self.__toposort.append(element[0], element[1])
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\plspm\util.py", line 137, in append
    self.__indegree[dest] += 1
TypeError: unhashable type: 'list'
2021-11-18 17:13:51,165 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:78]
2021-11-18 17:13:52,056 ERROR: Exception on /new_study/data_analysis/7431d4a5-bbe8-47c2-828f-877210b9cceb [GET] [in C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\noudy\PycharmProjects\PLS\app\new_study\routes.py", line 825, in data_analysis
    structure.add_path([corevariable.abbreviation], [influenced_variables])
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\plspm\config.py", line 49, in add_path
    self.__toposort.append(element[0], element[1])
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\plspm\util.py", line 137, in append
    self.__indegree[dest] += 1
TypeError: unhashable type: 'list'
2021-11-18 17:14:50,176 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:78]
2021-11-18 17:14:51,785 ERROR: Exception on /new_study/data_analysis/7431d4a5-bbe8-47c2-828f-877210b9cceb [GET] [in C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\noudy\PycharmProjects\PLS\app\new_study\routes.py", line 826, in data_analysis
    structure.add_path([corevariable.abbreviation], [influenced_variables])
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\plspm\config.py", line 49, in add_path
    self.__toposort.append(element[0], element[1])
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\plspm\util.py", line 137, in append
    self.__indegree[dest] += 1
TypeError: unhashable type: 'list'
2021-11-18 17:15:35,182 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:78]
2021-11-18 17:15:35,503 ERROR: Exception on /new_study/data_analysis/7431d4a5-bbe8-47c2-828f-877210b9cceb [GET] [in C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\noudy\PycharmProjects\PLS\app\new_study\routes.py", line 827, in data_analysis
    structure.add_path([corevariable.abbreviation], [influenced_variables])
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\plspm\config.py", line 49, in add_path
    self.__toposort.append(element[0], element[1])
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\plspm\util.py", line 137, in append
    self.__indegree[dest] += 1
TypeError: unhashable type: 'list'
2021-11-18 17:17:54,759 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:78]
