2021-11-11 10:31:50,709 ERROR: Exception on /auth/login [GET] [in C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\noudy\PycharmProjects\PLS\app\auth\routes.py", line 28, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\auth\login.html", line 2, in top-level template code
    {% from 'bootstrap/form.html' import render_form, render_field %}
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\base_logged_out.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/base.html
2021-11-11 10:36:07,645 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:77]
2021-11-11 10:36:08,342 ERROR: Exception on /auth/login [GET] [in C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\noudy\PycharmProjects\PLS\app\auth\routes.py", line 28, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\auth\login.html", line 2, in top-level template code
    {% from 'bootstrap/form.html' import render_form, render_field %}
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\base_logged_out.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\base.html", line 19, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\base_logged_out.html", line 36, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\auth\login.html", line 9, in block 'app_content'
    {{ wtf.quick_form(form) }}
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2021-11-11 10:38:31,919 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:77]
2021-11-11 10:38:34,005 ERROR: Exception on /auth/login [GET] [in C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\noudy\PycharmProjects\PLS\app\auth\routes.py", line 28, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\auth\login.html", line 2, in top-level template code
    {% from 'bootstrap/form.html' import render_form, render_field %}
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\base_logged_out.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\base.html", line 19, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\base_logged_out.html", line 36, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\noudy\PycharmProjects\PLS\app\templates\auth\login.html", line 9, in block 'app_content'
    {{ wtf.quick_form(form) }}
  File "C:\Users\noudy\PycharmProjects\untitled2\PLS\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2021-11-11 10:39:09,095 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:77]
2021-11-11 10:42:24,905 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:77]
2021-11-11 10:47:57,617 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:77]
2021-11-11 10:48:45,184 INFO: Microblog startup [in C:\Users\noudy\PycharmProjects\PLS\app\__init__.py:77]
